version: '3.8'

services:
  mysql:
    build:
      context: ./database
    container_name: oem-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Pa55w0rd
      MYSQL_DATABASE: oem-db
      MYSQL_USER: oem
      MYSQL_PASSWORD: Pa55w0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
